function [x,y] = readmpudata(workbookFile)
%IMPORTFILE Import data from a spreadsheet
%   DATA = IMPORTFILE(FILE) reads all numeric data from the first worksheet
%   in the Microsoft Excel spreadsheet file named FILE and returns the
%   numeric data.
%
%   DATA = IMPORTFILE(FILE,SHEET) reads from the specified worksheet.
%
%   DATA = IMPORTFILE(FILE,SHEET,RANGE) reads from the specified worksheet
%   and from the specified RANGE. Specify RANGE using the syntax
%   'C1:C2',where C1 and C2 are opposing corners of the region.%
% Example:
%   Untitled = importfile('7. France.xlsx','????1','B2:E135');
%
%   See also XLSREAD.

% Auto-generated by MATLAB on 2019/12/01 01:46:16

%% Input handling

sheetName = 1;
range = 'b:e';

%% Import the data
data = xlsread(workbookFile, sheetName, range);

row=length(data);

y=data(:,2);

data(:,2)=[];

x=data;

end
